"""Alterando colunas

Revision ID: 11209f19a644
Revises: 
Create Date: 2025-09-17 17:18:49.116212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11209f19a644'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Expenses', sa.Column('subcategory', sa.String(), nullable=True))
    op.create_index(op.f('ix_Expenses_subcategory'), 'Expenses', ['subcategory'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Expenses_subcategory'), table_name='Expenses')
    op.drop_column('Expenses', 'subcategory')
    # ### end Alembic commands ###
