"""2a_migration

Revision ID: 58b6158e191e
Revises: d52d47bb9c33
Create Date: 2025-09-24 17:46:02.270286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58b6158e191e'
down_revision: Union[str, Sequence[str], None] = 'd52d47bb9c33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Categorys', sa.Column('type', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Categorys', 'type')
    # ### end Alembic commands ###
