"""novos campos transaction

Revision ID: c93148657a97
Revises: 58b6158e191e
Create Date: 2025-10-06 20:34:25.288507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c93148657a97'
down_revision: Union[str, Sequence[str], None] = '58b6158e191e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Transactions', sa.Column('is_recurring',
                  sa.Boolean(), nullable=False, server_default="False"))
    op.add_column('Transactions', sa.Column(
        'recurrence_type', sa.String(), nullable=True))
    op.add_column('Transactions', sa.Column('auto_generated',
                  sa.Boolean(), nullable=False, server_default="False"))
    op.add_column('Transactions', sa.Column(
        'parent_recurring_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Transactions', 'parent_recurring_id')
    op.drop_column('Transactions', 'auto_generated')
    op.drop_column('Transactions', 'recurrence_type')
    op.drop_column('Transactions', 'is_recurring')
    # ### end Alembic commands ###
