"""1a_migration

Revision ID: d52d47bb9c33
Revises: 
Create Date: 2025-09-24 17:29:16.027115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd52d47bb9c33'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Categorys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('subcategorys', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category')
    )
    op.create_table('Transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('money', sa.Float(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('subcategory', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('event_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Transactions_category'), 'Transactions', ['category'], unique=False)
    op.create_index(op.f('ix_Transactions_id'), 'Transactions', ['id'], unique=False)
    op.create_index(op.f('ix_Transactions_subcategory'), 'Transactions', ['subcategory'], unique=False)
    op.create_index(op.f('ix_Transactions_type'), 'Transactions', ['type'], unique=False)
    op.create_index(op.f('ix_Transactions_userId'), 'Transactions', ['userId'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Transactions_userId'), table_name='Transactions')
    op.drop_index(op.f('ix_Transactions_type'), table_name='Transactions')
    op.drop_index(op.f('ix_Transactions_subcategory'), table_name='Transactions')
    op.drop_index(op.f('ix_Transactions_id'), table_name='Transactions')
    op.drop_index(op.f('ix_Transactions_category'), table_name='Transactions')
    op.drop_table('Transactions')
    op.drop_table('Categorys')
    # ### end Alembic commands ###
